[workspace]
authors = ["Agustin Corbat <acorbat@df.uba.ar>"]
channels = ["conda-forge"]
name = "workshop_segmentation_quantification"
version = "0.1.0"
description = "Taller introductorio a análisis de bioimágenes con Napari"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
install-assistant = "pixi install --environment assistant"
setup = { depends-on = ["install-assistant", "download-data"] }
download-data = """
curl -L https://zenodo.org/records/15175309/files/Nuclei_no_avg.nd2?download=1 --output data/nuclei.nd2 --create-dirs --skip-existing
curl -L https://zenodo.org/records/15175309/files/Tissue_no_avg.nd2?download=1 --output data/tissue.nd2 --create-dirs --skip-existing
curl -L "https://drive.usercontent.google.com/download?id=1do6JdOqgrBH_YFjpMYkPSEN9BFgl0iwD&confirm=xxx" --output data/CEL3_pml-GFP.tif --create-dirs --skip-existing
curl -L "https://drive.usercontent.google.com/download?id=1fVEGYjcTYcKy2Jah1pEL3YrHQy40d1LG&confirm=xxx" --output data/CEL3_ACTINA-texasRed.tif --create-dirs --skip-existing
curl -L "https://drive.usercontent.google.com/download?id=1w66BYKIZmauK1oXNnmR1MjIwbHXwt_0g&confirm=xxx" --output data/CEL1_pml-GFP.tif --create-dirs --skip-existing
curl -L "https://drive.usercontent.google.com/download?id=1pZoN5Mj5AOm4PgrdBoU1LvBB2sAA8IJ1&confirm=xxx" --output data/CEL3_nu-DAPI.tif --create-dirs --skip-existing
curl -L "https://drive.usercontent.google.com/download?id=1gG3FULwuE7hkFAtMgnVOX8G4HREf6z74&confirm=xxx" --output data/CEL2_nu-DAPI.tif --create-dirs --skip-existing
curl -L "https://drive.usercontent.google.com/download?id=1t8woPQEUYx2ZY13IJd_vPDrGNTtpxosT&confirm=xxx" --output data/CEL2_pml-GFP.tif --create-dirs --skip-existing
curl -L "https://drive.usercontent.google.com/download?id=17w81LFVYk_FKdc0bdJ3nVJ445zWqZomp&confirm=xxx" --output data/CEL1_ACTINA-texasRed.tif --create-dirs --skip-existing
curl -L "https://drive.usercontent.google.com/download?id=1Hr8Im-2rqZjp-b1phL0kdt4EY0Ugdq6j&confirm=xxx" --output data/CEL2_ACTINA-texasRed.tif --create-dirs --skip-existing
curl -L "https://drive.usercontent.google.com/download?id=1xdj-hJtpUQDA8giCpjUkvtORhBws3tie&confirm=xxx" --output data/CEL1_nu-DAPI.tif --create-dirs --skip-existing
"""

[feature.assistant.dependencies]
python = "3.10.*"

napari = "0.6.*"
napari-assistant = "0.6.*"
napari-bioformats = ">=0.3.0.post0,<0.4"

# procesamiento con scikit-image
scikit-image = "*"
numpy = "*"
scipy = "*"

# herramientas de segmentación compatibles con el asistente
napari-segment-blobs-and-things-with-membranes = "==0.3.1"

# regionprops (medición)
napari-skimage-regionprops = "*"

# backend GUI
pyqt = "*"
qtpy = "*"
magicgui = "*"
jupytext = ">=1.19.1,<2"
jupyterlab = ">=4.5.4,<5"
matplotlib = ">=3.10.9,<4"
ipywidgets = ">=8.1.8,<9"

[environments]
assistant = ["assistant"]
